theme = "ayu_dark"

[editor]
line-number = "relative"
true-color = true
scrolloff = 999
idle-timeout = 0
soft-wrap = { enable = true }
mouse = false
completion-timeout = 5
completion-trigger-len = 1
jump-label-alphabet = "ntdhseriaobkjlguvmfycxzwqp"
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[editor.gutters]
layout = ["line-numbers", "spacer", "diff"]

[editor.word-completion]
trigger-length = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'

[keys.select]
W = 'extend_next_sub_word_start'
B = 'extend_prev_sub_word_start'
E = 'extend_next_sub_word_end'

[keys.normal."space"]
c = "file_picker_in_current_buffer_directory"
