theme = "ayu_dark"

[editor]
line-number = "relative"
true-color = true
scrolloff = 999
idle-timeout = 0
soft-wrap = { enable = true }
mouse = false
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"

[keys.normal."space"]
c = "file_picker_in_current_buffer_directory"
