# Git aliases
alias amend="git commit --amend"
alias autosquash='git rebase -i --autosquash'
alias clean='git clean -df'
alias co='gco'
alias develop='git checkout develop'
alias fetch='git fetch'
alias ff='fixup; git push --force origin $(git_branch_name)'
alias fp='git fetch && git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)'
alias ga='git add -A'
alias gaf='git add $(gf)'
alias gag='git add -A && git commit --amend --no-edit && git push -f'
alias gagc='git add -A && git commit -a'
alias gbd='git branch -D $(gb)'
alias gc='git commit -v'
alias gco='git checkout'
alias gdc='git diff --cached | less -R'
alias gdm='git diff master || git diff main | less -R'
alias gdp='git diff --patience | less -R'
alias ge='git edit'
alias gl='git lg'
alias gld='git lg -p --since="1 day ago"'
alias glm="git log --pretty=format:'%h | %cd | %an | %s' -n 15"
alias glo='git log --oneline -n 15'
alias glp='git lg -p | less -R'
alias gls='git log --stat -n 5'
alias gp='git push'
alias gpl='git pull --rebase --autostash origin $(git rev-parse --abbrev-ref HEAD)'
alias gpo='git push origin'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grh='git reset HEAD^'
alias grs='git rebase --skip'
alias gs='git show | less -R'
alias lg='lazygit'

# Bundle aliases
alias b="bundle"
alias be="bundle exec"
alias bi="bundle install"
alias bu='bundle update'

# Rails aliases
alias br='bin/rspec'
alias dbprep='rdm && rdtp'
alias r='bin/rails'
alias rc='bin/rails console'
alias rdc='bin/rails db:create'
alias rdm='bin/rails db:migrate'
alias rdtp='bin/rails db:test:prepare'
alias rff='bundle exec rspec --fail-fast'
alias rr='bin/rails routes'
alias rs='bundle check && bin/rails s'
alias rt='bin/rails test'
alias ss='spring stop'
alias ssbr='spring stop && bin/rspec'

# Docker aliases
alias dcb='docker-compose build'
alias dcl="docker-compose logs -f"
alias dco="docker-compose"
alias dcp='docker container prune'
alias dcu="docker-compose up -d"
alias di='docker images'
alias dimp='docker image prune'
alias dp='docker ps'
alias dpa='docker ps -a'
alias drm='docker rm'
alias drmi='docker rmi'

# GitHub aliases
alias hb='gh browse'
alias hc='hub compare'
alias hpr='gh pr create'
alias hps='gh pr view --web'
alias merge='gh pr merge --squash --delete-branch && pl'
alias ready='gh pr ready'
alias review='PAGER=less gh pr diff'

# Navigation and utility aliases
alias c='clear'
alias cdh='cd ~'
alias dot='cd ~/code/git/dotfiles'
alias e='exit'
alias k9='kill -9'
alias killbeam='killall -9 beam.smp'
alias killruby='killall -9 ruby'
alias l='ls -al'
alias lo='glo'
alias ls="ls -AFG"
alias m='git checkout master || git checkout main'
alias master='git checkout master || git checkout main'
alias mon='nodemon '
alias notes='cd ~/Library/CloudStorage/Dropbox/notes/'
alias on3000='lsof -i tcp:3000'
alias p8='ping 8.8.8.8'
alias p='gp'
alias pf='gpf'
alias pjson='python -m json.tool'
alias pl='gpl'
alias repush='git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) && git push'
alias reset='git reset --hard head'
alias stash='git stash'
alias stashclear='git stash clear'
alias stashls='git stash list'
alias stashpop='git stash pop'
alias stashshow='git stash show stash@{0}  -p'
alias sync='git add -u . && git commit -m "Minor changes. Commit message skipped." && repush'
alias t='tmux -2'
alias tmux='tmux -2'
