#!/bin/bash

# Shortcut for changing directories
alias ...="cd ../.."                        # go up parent dir twice
alias ....="cd ../../.."                    # .. thrice
alias .....="cd ../../../.."                # .. four times
alias ......="cd ../../../../.."            # .. five times
alias cd-="cd -"
alias cd.='cd ..'
alias cd..="cd .."
alias dot='cd ~/code/git/dotfiles'

# For speed me up
alias -g G='| grep'
alias -g L='| less'
alias -g M='| more'
alias amend="git commit --amend"
alias autosquash='git rebase -i --autosquash'
alias be="bundle exec"
alias bi="bundle install"
alias c='clear'
alias cdh='cd ~'
alias cdl='cd ~/.config/nvim'
alias dcl="docker-compose logs -f"
alias dco="docker-compose"
alias dcu="docker-compose up -d"
alias deploy='rake deploy:archive'
alias dp='docker ps'
alias dpa='docker ps -a'
alias e='exit'
alias fetch='git fetch'
alias fixup='git commit --fixup'
alias fp='git fetch && git pull --rebase'
alias fuck='eval $(thefuck $(fc -ln -1))'
alias g='git status'
alias ga='git add -A'
alias gaf='git add $(gf)'
alias gag='git add -A && git commit -m'
alias gbd='git branch -D $(gb)'
alias gc='git commit -m'
alias gcb='git checkout $(gb)'
alias gcf='git checkout $(gf)'
alias gch='git checkout $(gh)'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdf='git diff $(gf)'
alias gdh='git diff $(gh)'
alias gl='git lg'
alias gld='git lg -p --since="1 day ago"'
alias glp='git lg -p'
alias gp='git push'
alias gpl='git pull --rebase'
alias gpo='git push origin'
alias gs='git status --short --branch'
alias gto='git-open'
alias gv='vim +GV +"autocmd BufWipeout <buffer> qall"'
alias hpr='hub pull-request'
alias ll="ls -FGlh"
alias ls="ls -AFG"
alias master='git checkout master'
alias mon='nodemon '
alias y='yarn'
alias yi='yarn install'
alias yt='yarn test'
alias p8='ping 8.8.8.8'
alias rc='bin/rails console'
alias rdm='bin/rake db:migrate'
alias reset='git reset --hard head'
alias retag='ctags -a -Rf .git/tags --exclude=.git --exclude="*.min.js" --exclude=node_modules --exclude=admin/node_modules --exclude=tmp 2>/dev/null'
alias rs='bundle check && rails s -p 3001'
alias server='NODE_ENV=development nodemon --inspect server.js'
alias stash='git stash'
alias stashclear='git stash clear'
alias stashls='git stash list'
alias stashpop='git stash pop'
alias stashshow='git stash show stash@{0}  -p'
alias t='tmux -2'
alias tmux='tmux -2'
alias u='cd ..'
alias v="nvim"
alias vim='nvim'
alias vimn='nvim -u NONE'
