#!/bin/bash

export GOPATH=~/gosrc
mkdir -p $GOPATH
export PATH=/usr/local/bin:$GOPATH/bin:$PATH
export LANG=en_US.UTF-8

# Ruby environment config
if [ -x "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
fi

export CDPATH=$CDPATH:$HOME/code/git:$HOME/code

# Don't exit on ctrl-d
set -o ignoreeof

# FZF options
export FZF_CTRL_T_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden --bind '?:toggle-preview'"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
command -v blsd > /dev/null && export FZF_ALT_C_COMMAND='blsd'
command -v tree > /dev/null && export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
